apiVersion: v1
kind: Secret
metadata:
  name: capi-oke-credentials
  namespace: verrazzano-capi
type: Opaque
data:
  tenancy: $${OCI_TENANCY_ID_B64}
  user: $${OCI_USER_ID_B64}
  region: $${OCI_REGION_B64}
  key: $${OCI_CREDENTIALS_KEY_B64}
  fingerprint: $${OCI_CREDENTIALS_FINGERPRINT_B64}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: OCIClusterIdentity
metadata:
  name: oke-cluster-identity
  namespace: verrazzano-capi
spec:
  type: UserPrincipal
  principalSecret:
    name: capi-oke-credentials
    namespace: verrazzano-capi
  allowedNamespaces: {}