apiVersion: install.verrazzano.io/v1beta1
kind: Verrazzano
metadata:
  name: admin
spec:
  profile: ${profile}
  environmentName: admin
  components:
    argoCD:
      enabled: true
    clusterOperator:
      overrides:
      - values:
          syncClusters:
            enabled: true
            clusterSelector:
              matchExpressions:
              - key: vz
                operator: In
                values: [oci]
    dns:
      oci:
        ociConfigSecret: oci
        dnsZoneCompartmentOCID: ${compartment_id}
        dnsZoneOCID: ${dns_zone_id}
        dnsZoneName: ${dns_zone_name}
    ingressNGINX:
      type: LoadBalancer
      overrides:
      - values:
          controller:
            service:
              annotations:
                service.beta.kubernetes.io/oci-load-balancer-shape: "100Mbps"
                service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "25"
                service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "50"
                service.beta.kubernetes.io/oci-load-balancer-security-list-management-mode: "None"
                oci.oraclecloud.com/oci-network-security-groups: "${public_nsg}"
    istio:
      overrides:
      - values:
          apiVersion: install.istio.io/v1alpha1
          kind: IstioOperator
          spec:
            components:
              ingressGateways:
                - enabled: true
                  name: istio-ingressgateway
                  k8s:
                    serviceAnnotations:
                      service.beta.kubernetes.io/oci-load-balancer-shape: "100Mbps"
                      service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "25"
                      service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "50"
                      service.beta.kubernetes.io/oci-load-balancer-security-list-management-mode: "None"
                      oci.oraclecloud.com/oci-network-security-groups: "${public_nsg}"