apiVersion: install.verrazzano.io/v1beta1
kind: Verrazzano
metadata:
  name: ${cluster}
spec:
  profile: managed-cluster
  environmentName: ${cluster}
  components:
    dns:
      oci:
        ociConfigSecret: oci
        dnsZoneCompartmentOCID: ${compartment_id}
        dnsZoneOCID: ${dns_zone_id}
        dnsZoneName: ${dns_zone_name}
    ingressNGINX:
      type: LoadBalancer
      overrides:
      - values:
          controller:
            service:
              annotations:
                service.beta.kubernetes.io/oci-load-balancer-internal: "${control_plane}"
                service.beta.kubernetes.io/oci-load-balancer-shape: "${lb_shape}"
                service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "${flex_min}"
                service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "${flex_max}"
                service.beta.kubernetes.io/oci-load-balancer-security-list-management-mode: "None"
                oci.oraclecloud.com/oci-network-security-groups: "${control_plane_nsg}"
    istio:
      overrides:
      - values:
          apiVersion: install.istio.io/v1alpha1
          kind: IstioOperator
          spec:
            components:
              ingressGateways:
                - name: istio-ingressgateway
                  enabled: true
                  k8s:
                    serviceAnnotations:
                      service.beta.kubernetes.io/oci-load-balancer-internal: "${data_plane}"                    
                      service.beta.kubernetes.io/oci-load-balancer-shape: "${lb_shape}"
                      service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "${flex_min}"
                      service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "${flex_max}"
                      service.beta.kubernetes.io/oci-load-balancer-security-list-management-mode: "None"
                      oci.oraclecloud.com/oci-network-security-groups: "${data_plane_nsg}"