apiVersion: install.verrazzano.io/v1beta1
kind: Verrazzano
metadata:
  name: ${cluster}
spec:
  profile: managed-cluster
  environmentName: ${cluster}
  components:
    coherenceOperator:
      enabled: false
    dns:
      oci:
        ociConfigSecret: oci
        dnsZoneCompartmentOCID: ${compartment_id}
        dnsZoneOCID: ${dns_zone_id}
        dnsZoneName: ${dns_zone_name}
    ingressNGINX:
      type: LoadBalancer
      overrides:
      - values:
          controller:
            service:
              annotations:
                service.beta.kubernetes.io/oci-load-balancer-internal: "${control_plane}"
                service.beta.kubernetes.io/oci-load-balancer-shape: "${lb_shape}"
                service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "${flex_min}"
                service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "${flex_max}"
                service.beta.kubernetes.io/oci-load-balancer-security-list-management-mode: "None"
                oci.oraclecloud.com/oci-network-security-groups: "${control_plane_nsg}"
    istio:
      overrides:
      - values:
          apiVersion: install.istio.io/v1alpha1
          kind: IstioOperator
          spec:
            values:
              global:
                meshID: ${mesh_id}
                multiCluster:
                  clusterName: ${cluster_name}
                network: ${mesh_network}
            components:
              egressGateways:
                - name: istio-egressgateway
                  enabled: true
              ingressGateways:
                - name: istio-ingressgateway
                  enabled: true
                  k8s:
                    serviceAnnotations:
                      service.beta.kubernetes.io/oci-load-balancer-internal: "${data_plane}"                    
                      service.beta.kubernetes.io/oci-load-balancer-shape: "${lb_shape}"
                      service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "${flex_min}"
                      service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "${flex_max}"
                      service.beta.kubernetes.io/oci-load-balancer-security-list-management-mode: "None"
                      oci.oraclecloud.com/oci-network-security-groups: "${data_plane_nsg}"
                - name: istio-eastwestgateway
                  enabled: true
                  k8s:
                    serviceAnnotations:
                      service.beta.kubernetes.io/oci-load-balancer-internal: "true"
                      service.beta.kubernetes.io/oci-load-balancer-shape: "10Mbps"
                      service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "50"
                      service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
                      service.beta.kubernetes.io/oci-load-balancer-security-list-management-mode: "None"
                      oci.oraclecloud.com/oci-network-security-groups: "${int-nsg-id}"
                    env:
                    - name: ISTIO_META_REQUESTED_NETWORK_VIEW
                      value: ${mesh_network}
                    service:
                      ports:
                      - name: status-port
                        port: 15021
                        targetPort: 15021
                      - name: tls
                        port: 15443
                        targetPort: 15443
                      - name: tls-istiod
                        port: 15012
                        targetPort: 15012
                      - name: tls-webhook
                        port: 15017
                        targetPort: 15017
                  label:
                    app: istio-eastwestgateway
                    istio: eastwestgateway
                    topology.istio.io/network: ${mesh_network}
    kiali:
      enabled: true
    kubeStateMetrics:
      enabled: false
    velero:
      enabled: false
    weblogicOperator:
      enabled: false