baseURL = 'https://oracle-terraform-modules.github.io/terraform-oci-verrazzano'
languageCode = 'en-us'
title = 'Terraform module for Verrazzano on OCI'

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[params]
  BookSearch = false