baseURL = 'https://oracle-terraform-modules.github.io/terraform-oci-verrazzano/'
languageCode = 'en-us'
title = 'Terraform module for Verrazzano on OCI'
theme = "hugo-theme-relearn"

canonifyURLs = true

[markup]
  [markup.tableOfContents]
    endLevel = 5
    ordered = true
    startLevel = 1

[outputs]
  home = ["HTML", "RSS", "PRINT", "SEARCH"]
  section = ["HTML", "RSS", "PRINT"]
  page = ["HTML", "RSS", "PRINT"]
  
[params]
  alwaysopen = true
  showVisitedLinks = false
  disableBreadcrumb = false
  collapsibleMenu = true
  ordersectionsby = "weight"