baseURL = 'https://oracle-terraform-modules.github.io/terraform-oci-verrazzano/'
languageCode = 'en-us'
title = 'Terraform module for Verrazzano on OCI'
theme = "hugo-theme-relearn"

canonifyURLs = true

[markup]
  [markup.tableOfContents]
    endLevel = 5
    ordered = true
    startLevel = 1
  [markup.highlight]
    # if `guessSyntax = true`, there will be no unstyled code even if no language
    # was given BUT Mermaid and Math codefences will not work anymore! So this is a
    # mandatory setting for your site if you want to use Mermaid or Math codefences
    guessSyntax = false

    # choose a color theme or create your own
    style = "monokai"    

[outputs]
  home = ["HTML", "RSS", "PRINT", "SEARCH"]
  section = ["HTML", "RSS", "PRINT"]
  page = ["HTML", "RSS", "PRINT"]
  
[params]
  alwaysopen = true
  showVisitedLinks = false
  disableBreadcrumb = false
  collapsibleMenu = true
  ordersectionsby = "weight"