# Copyright (c) 2023 Oracle Corporation and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl

output "cluster_ids" {
  value = {
    # "johannesburg" = one(module.johannesburg[*].cluster_id)
    # "chuncheon"    = one(module.chuncheon[*].cluster_id)
    # "hyderabad"    = one(module.hyderabad[*].cluster_id)
    # "mumbai"       = one(module.mumbai[*].cluster_id)
    # "osaka"        = one(module.osaka[*].cluster_id)
    # "seoul"        = one(module.seoul[*].cluster_id)
    # "singapore"    = one(module.singapore[*].cluster_id)
    # "tokyo"        = one(module.tokyo[*].cluster_id)
    # "amsterdam"    = one(module.amsterdam[*].cluster_id)
    # "frankfurt"    = one(module.frankfurt[*].cluster_id)
    # "london"       = one(module.london[*].cluster_id)
    # "madrid"       = one(module.madrid[*].cluster_id)
    # "marseille"    = one(module.marseille[*].cluster_id)
    # "milan"        = one(module.milan[*].cluster_id)
    # "newport"      = one(module.newport[*].cluster_id)
    # "paris"        = one(module.paris[*].cluster_id)
    # "stockholm"    = one(module.stockholm[*].cluster_id)
    # "zurich"       = one(module.zurich[*].cluster_id)
    # "abudhabi"     = one(module.abudhabi[*].cluster_id)
    # "dubai"        = one(module.dubai[*].cluster_id)
    # "jeddah"       = one(module.jeddah[*].cluster_id)
    # "jerusalem"    = one(module.jerusalem[*].cluster_id)
    # "melbourne"    = one(module.melbourne[*].cluster_id)
    # "sydney"       = one(module.sydney[*].cluster_id)
    "melbourne" = one(module.melbourne[*].cluster_id)
    "sydney"    = one(module.sydney[*].cluster_id)
    # "santiago"     = one(module.santiago[*].cluster_id)
    # "saupaulo"     = one(module.saupaulo[*].cluster_id)
    # "vinhedo"      = one(module.vinhedo[*].cluster_id)
    # "ashburn"      = one(module.ashburn[*].cluster_id)
    # "chicago"      = one(module.chicago[*].cluster_id)
    # "montreal"     = one(module.montreal[*].cluster_id)
    # "phoenix"      = one(module.phoenix[*].cluster_id)
    # "queretaro"    = one(module.queretaro[*].cluster_id)
    # "sanjose"      = one(module.sanjose[*].cluster_id)
    # "toronto"      = one(module.toronto[*].cluster_id)
  }
}

output "int_nsg_ids" {
  value = {
    # "johannesburg" = one(module.johannesburg[*].int_lb_nsg)
    # "chuncheon"    = one(module.chuncheon[*].int_lb_nsg)
    # "hyderabad"    = one(module.hyderabad[*].int_lb_nsg)
    # "mumbai"       = one(module.mumbai[*].int_lb_nsg)
    # "osaka"        = one(module.osaka[*].int_lb_nsg)
    # "seoul"        = one(module.seoul[*].int_lb_nsg)
    # "singapore"    = one(module.singapore[*].int_lb_nsg)
    # "tokyo"        = one(module.tokyo[*].int_lb_nsg)
    # "amsterdam"    = one(module.amsterdam[*].int_lb_nsg)
    # "frankfurt"    = one(module.frankfurt[*].int_lb_nsg)
    # "london"       = one(module.london[*].int_lb_nsg)
    # "madrid"       = one(module.madrid[*].int_lb_nsg)
    # "marseille"    = one(module.marseille[*].int_lb_nsg)
    # "milan"        = one(module.milan[*].int_lb_nsg)
    # "newport"      = one(module.newport[*].int_lb_nsg)
    # "paris"        = one(module.paris[*].int_lb_nsg)
    # "stockholm"    = one(module.stockholm[*].int_lb_nsg)
    # "zurich"       = one(module.zurich[*].int_lb_nsg)
    # "abudhabi"     = one(module.abudhabi[*].int_lb_nsg)
    # "dubai"        = one(module.dubai[*].int_lb_nsg)
    # "jeddah"       = one(module.jeddah[*].int_lb_nsg)
    # "jerusalem"    = one(module.jerusalem[*].int_lb_nsg)
    "melbourne" = one(module.melbourne[*].int_lb_nsg)
    "sydney"    = one(module.sydney[*].int_lb_nsg)
    # "santiago"     = one(module.santiago[*].int_lb_nsg)
    # "saupaulo"     = one(module.saupaulo[*].int_lb_nsg)
    # "vinhedo"      = one(module.vinhedo[*].int_lb_nsg)
    # "ashburn"      = one(module.ashburn[*].int_lb_nsg)
    # "chicago"      = one(module.chicago[*].int_lb_nsg)
    # "montreal"     = one(module.montreal[*].int_lb_nsg)
    # "phoenix"      = one(module.phoenix[*].int_lb_nsg)
    # "queretaro"    = one(module.queretaro[*].int_lb_nsg)
    # "sanjose"      = one(module.sanjose[*].int_lb_nsg)
    # "toronto"      = one(module.toronto[*].int_lb_nsg)       
  }
}

output "pub_nsg_ids" {
  value = {
    # "johannesburg" = one(module.johannesburg[*].pub_lb_nsg)
    # "chuncheon"    = one(module.chuncheon[*].pub_lb_nsg)
    # "hyderabad"    = one(module.hyderabad[*].pub_lb_nsg)
    # "mumbai"       = one(module.mumbai[*].pub_lb_nsg)
    # "osaka"        = one(module.osaka[*].pub_lb_nsg)
    # "seoul"        = one(module.seoul[*].pub_lb_nsg)
    # "singapore"    = one(module.singapore[*].pub_lb_nsg)
    # "tokyo"        = one(module.tokyo[*].pub_lb_nsg)
    # "amsterdam"    = one(module.amsterdam[*].pub_lb_nsg)
    # "frankfurt"    = one(module.frankfurt[*].pub_lb_nsg)
    # "london"       = one(module.london[*].pub_lb_nsg)
    # "madrid"       = one(module.madrid[*].pub_lb_nsg)
    # "marseille"    = one(module.marseille[*].pub_lb_nsg)
    # "milan"        = one(module.milan[*].pub_lb_nsg)
    # "newport"      = one(module.newport[*].pub_lb_nsg)
    # "paris"        = one(module.paris[*].pub_lb_nsg)
    # "stockholm"    = one(module.stockholm[*].pub_lb_nsg)
    # "zurich"       = one(module.zurich[*].pub_lb_nsg)
    # "abudhabi"     = one(module.abudhabi[*].pub_lb_nsg)
    # "dubai"        = one(module.dubai[*].pub_lb_nsg)
    # "jeddah"       = one(module.jeddah[*].pub_lb_nsg)
    # "jerusalem"    = one(module.jerusalem[*].pub_lb_nsg)
    "melbourne" = one(module.melbourne[*].pub_lb_nsg)
    "sydney"    = one(module.sydney[*].pub_lb_nsg)
    # "santiago"     = one(module.santiago[*].pub_lb_nsg)
    # "saupaulo"     = one(module.saupaulo[*].pub_lb_nsg)
    # "vinhedo"      = one(module.vinhedo[*].pub_lb_nsg)
    # "ashburn"      = one(module.ashburn[*].pub_lb_nsg)
    # "chicago"      = one(module.chicago[*].pub_lb_nsg)
    # "montreal"     = one(module.montreal[*].pub_lb_nsg)
    # "phoenix"      = one(module.phoenix[*].pub_lb_nsg)
    # "queretaro"    = one(module.queretaro[*].pub_lb_nsg)
    # "sanjose"      = one(module.sanjose[*].pub_lb_nsg)
    # "toronto"      = one(module.toronto[*].pub_lb_nsg)       
  }
}

output "int_lb_subnet_ids" {
  value = {
    # "johannesburg" = coalesce(lookup(module.johannesburg[0].subnet_ids,"int_lb"))
    # "chuncheon"    = coalesce(lookup(module.chuncheon[0].subnet_ids,"int_lb"))
    # "hyderabad"    = coalesce(lookup(module.hyderabad[0].subnet_ids,"int_lb"))
    # "mumbai"       = coalesce(lookup(module.mumbai[0].subnet_ids,"int_lb"))
    # "osaka"        = coalesce(lookup(module.osaka[0].subnet_ids,"int_lb"))
    # "seoul"        = coalesce(lookup(module.seoul[0].subnet_ids,"int_lb"))
    # "singapore"    = coalesce(lookup(module.singapore[0].subnet_ids,"int_lb"))
    # "tokyo"        = coalesce(lookup(module.tokyo[0].subnet_ids,"int_lb"))
    # "amsterdam"    = coalesce(lookup(module.amsterdam[0].subnet_ids,"int_lb"))
    # "frankfurt"    = coalesce(lookup(module.frankfurt[0].subnet_ids,"int_lb"))
    # "london"       = coalesce(lookup(module.london[0].subnet_ids,"int_lb"))
    # "madrid"       = coalesce(lookup(module.madrid[0].subnet_ids,"int_lb"))
    # "marseille"    = coalesce(lookup(module.marseille[0].subnet_ids,"int_lb"))
    # "milan"        = coalesce(lookup(module.milan[0].subnet_ids,"int_lb"))
    # "newport"      = coalesce(lookup(module.newport[0].subnet_ids,"int_lb"))
    # "paris"        = coalesce(lookup(module.paris[0].subnet_ids,"int_lb"))
    # "stockholm"    = coalesce(lookup(module.stockholm[0].subnet_ids,"int_lb"))
    # "zurich"       = coalesce(lookup(module.zurich[0].subnet_ids,"int_lb"))
    # "abudhabi"     = coalesce(lookup(module.abudhabi[0].subnet_ids,"int_lb"))
    # "dubai"        = coalesce(lookup(module.dubai[0].subnet_ids,"int_lb"))
    # "jeddah"       = coalesce(lookup(module.jeddah[0].subnet_ids,"int_lb"))
    # "jerusalem"    = coalesce(lookup(module.jerusalem[0].subnet_ids,"int_lb"))
    "melbourne" = coalesce(lookup(module.melbourne[0].subnet_ids, "int_lb"))
    # "sydney"       = coalesce(lookup(module.sydney[0].subnet_ids,"int_lb"))
    # "santiago"     = coalesce(lookup(module.santiago[0].subnet_ids,"int_lb"))
    # "saupaulo"     = coalesce(lookup(module.saupaulo[0].subnet_ids,"int_lb"))
    # "vinhedo"      = coalesce(lookup(module.vinhedo[0].subnet_ids,"int_lb"))
    # "ashburn"      = coalesce(lookup(module.ashburn[0].subnet_ids,"int_lb"))
    # "chicago"      = coalesce(lookup(module.chicago[0].subnet_ids,"int_lb"))
    # "montreal"     = coalesce(lookup(module.montreal[0].subnet_ids,"int_lb"))
    # "phoenix"      = coalesce(lookup(module.phoenix[0].subnet_ids,"int_lb"))
    # "queretaro"    = coalesce(lookup(module.queretaro[0].subnet_ids,"int_lb"))
    # "sanjose"      = coalesce(lookup(module.sanjose[0].subnet_ids,"int_lb"))
    # "toronto"      = coalesce(lookup(module.toronto[0].subnet_ids,"int_lb"))
  }
}
