name: Publish Terraform OCI Verrazzano Module Book
on:
  # Rebuild docs when a release is published
  push:
    branches: 
      - "main"
  # Enable manual trigger
  workflow_dispatch:

jobs:
  install-mdbook:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        continue-on-error: true
        id: cache-mdbook
        with:
          key: mdbook
          path: ./cargo/**/*
      - if: ${{ steps.cache-mdbook.outputs.cache-hit != 'true' }}
        name: Install mdbook
        env:
          CARGO_HOME: ./cargo
        run: cargo install mdbook-admonish mdbook-variables mdbook mdbook-toc mdbook-pagetoc
  build-and-deploy:
    needs: [install-mdbook]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        continue-on-error: true
        with:
          key: mdbook
          path: ./cargo/**/*
      - name: Generate docs
        shell: bash
        env:
          CARGO_HOME: ./cargo
        run: |
          export PATH=`pwd`/cargo/bin:${PATH}
          make mdbuild
          touch ./docs/book/.nojekyll

      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v1
        with:
          path: './docs/book'
      - uses: actions/deploy-pages@v2
        id: deployment          
