name: Publish Documentation
on:
  push:
    branches:
      - "main"
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  install-mdbook:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        continue-on-error: true
        id: cache-mdbook
        with:
          key: mdbook
          path: ./cargo/**/*
      - if: ${{ steps.cache-mdbook.outputs.cache-hit != 'true' }}
        name: Install mdbook
        env:
          CARGO_HOME: ./cargo
        run: cargo install mdbook-admonish mdbook-variables mdbook mdbook-toc mdbook-pagetoc

  build-and-deploy:
    needs: [install-mdbook]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        continue-on-error: true
        with:
          key: mdbook
          path: ./cargo/**/*

      - name: Generate docs
        shell: bash
        env:
          CARGO_HOME: ./cargo
        run: |
        # Build the HTML content
        mdbook build -d book/ docs/

        # Create and switch to the gh-pages work tree
        git worktree add gh-pages gh-pages
        cd $GITHUB_WORKSPACE/gh-pages

        git config user.name "GitHub Actions"
        git config user.email "oci-dax-tools_ww@oracle.com"

        # Delete the ref to avoid keeping history.
        git update-ref -d refs/heads/gh-pages
        rm -rf *

        mv $GITHUB_WORKSPACE/docs/book/* $GITHUB_WORKSPACE/gh-pages
        touch $GITHUB_WORKSPACE/gh-pages/.nojekyll

        git add .
        git commit -m "Deploy $GITHUB_SHA to gh-pages"
        git push --force-with-lease

      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v1
        with:
          path: './docs/book'
      - uses: actions/deploy-pages@v2
        id: deployment